<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(''); ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>
		
        <!-- Scripts -->
        <?= $this->headScript()
			->prependFile($this->basePath('js/jquery.min.js'))
        ?>
    </head>
    <body>
		<header style="text-align: center;">
			Auth Login Implementation
		</header><br/>
		<section style="text-align: center;">
			<?= $this->content ?>
		</section><br/>
		<footer style="text-align: center;">
			&copy; <a href="http://www.pluspair.com">Pluspair.com</a>
		</footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
